# Generated by Django 5.2.4 on 2025-08-20 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrdata',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='Meal',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='Qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='Time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='NameID',
        ),
        migrations.AddField(
            model_name='qrdata',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qr.employee'),
        ),
    ]
