# Generated by Django 5.2.4 on 2025-08-20 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_rename_date_qrdata_date_rename_meal_qrdata_meal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrdata',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='meal',
            new_name='Meal',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='quantity',
            new_name='Qty',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='time',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='company',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='employee',
        ),
        migrations.AddField(
            model_name='qrdata',
            name='NameID',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
