# Generated by Django 5.2.4 on 2025-08-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_rename_date_qrdata_date_rename_meal_qrdata_meal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrdata',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='Meal',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='NameID',
            new_name='name_id',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='Qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='qrdata',
            old_name='Time',
            new_name='time',
        ),
    ]
