# Generated by Django 5.2.4 on 2025-08-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_rename_date_qrdata_date_rename_meal_qrdata_meal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrdata',
            name='name_id',
        ),
        migrations.AddField(
            model_name='qrdata',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qr.employee'),
            preserve_default=False,
        ),
    ]
