# Generated by Django 5.2.4 on 2025-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_remove_qrdata_name_id_qrdata_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='name_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
