# Generated by Django 5.2.4 on 2025-08-20 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0009_remove_qrdata_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='name_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
