# Generated by Django 5.2.4 on 2025-08-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_qrdata_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrdata',
            name='employee',
        ),
    ]
