# Generated by Django 5.2.4 on 2025-08-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0011_remove_qrdata_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qr.employee'),
        ),
    ]
